### ISSUE TITLE
TreeView

### ISSUE THREAD

**Issue by Daguerreo** [OlivierLDff/QaterialGallery#5]
First let me say this project is awesome and real stunning :)

Have you considered to introduce a TreeView component?

**Comment by OlivierLDff** [comment]
That would be a cool and useful feature since qml lack of treeview support.
I can't give you any schedule on when i will do that.
I add components in this library when i need them in projects. Feel free to create a PR.

**Comment by Daguerreo** [comment]
I found an Accordion implementation on QtForum, it could be a nice starting point since Grecko snippet works quite well:

https://forum.qt.io/topic/81646/expandible-collapsible-pane-with-smooth-animation-in-qml/5

**Comment by OlivierLDff** [comment]
I added an implementation of TreeView if you are still interested https://github.com/OlivierLDff/Qaterial/pull/56
![Basic tree view](https://user-images.githubusercontent.com/17255804/88517561-4df11500-cfef-11ea-9588-72d76682cbbe.gif)
![jsonTreeView](https://user-images.githubusercontent.com/17255804/88517915-e38ca480-cfef-11ea-8f8e-107e51b38b06.gif)

**Comment by Daguerreo** [comment]
Checked in QaterialOnline. Works great!

**Comment by OlivierLDff** [comment]
I also added a basic FolderTreeModel since this is the main use of treeView
![image](https://user-images.githubusercontent.com/17255804/88570575-8ec34b00-d03c-11ea-8faa-510b7b4c5bc6.png)
