### ISSUE TITLE
qmake project

### ISSUE THREAD

**Issue by ssakone** [OlivierLDff/QaterialGallery#6]
Sa seras bien, si on pouvais l'utiliser avec qmake, étant nouveau avec cmake je galère comme un fou, sa marche mais,
mais je peux pas l'utiliser dans mes projects précédent trop de modification a faire

**Comment by OlivierLDff** [comment]
I answered you in Qaterial https://github.com/OlivierLDff/Qaterial/issues/55. What problem are you facing with cmake in your own projects?

**Comment by ssakone** [comment]
I want to move my projets on cmake
